// <auto-generated />
using System;
using EF_ToListAsync_AsAsyncEnumerable.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_ToListAsync_AsAsyncEnumerable.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20231013083437_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_ToListAsync_AsAsyncEnumerable.Data.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SomeProperty1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SomeProperty2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SomeProperty3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SomeProperty4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SomeProperty5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SomeProperty6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SomeProperty7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SomeProperty8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SomeProperty9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Entities");
                });
#pragma warning restore 612, 618
        }
    }
}
